# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kguiaddons': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/kitemmodels': '@stable'
    'frameworks/kitemmviews': '@stable'
    'frameworks/knewstuff': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kdelibs4support': '@stable'
    'frameworks/kdoctools': '@stable'
    'education/analitza': '@stable'
